### ISSUE TITLE
Gauss Rifle leaves behind trails until the map/save is reloaded

### ISSUE THREAD

**Issue by XenoTheStrange** [Chuckleberry-Finn/Vanilla-Weapons-Expanded#3]
These trails seem to cause lag.
Image enclosed:
![image](https://github.com/Chuckleberry-Finn/Vanilla-Weapons-Expanded/assets/48196283/22e7dea4-4102-48b3-97ab-45f8c19ff8d8)

**Comment by Chuckleberry-Finn** [comment]
Wrong game brother.
